# Файл автоматической установки Proxmox VE 9.1
[global]
keyboard = "en-us"
country = "ru"
fqdn = "pve-auto.local"
mailto = "admin@pve-auto.local"
timezone = "Europe/Moscow"
root_password = "mega_root_password"
root_ssh_keys = []
reboot_on_error = true

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk_list = ["sda"]
