[global]
keyboard = "en-us"
country = "ru"
fqdn = "pve-test.local"
mailto = "admin@localhost"
timezone = "Europe/Moscow"
root_password = "mega_root_password"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk_list = ["vda"]
